New Pull Request, initiated after Branch Protection Rule: Require conversation before Merge has been defined
SASdemo-maintainer2/SAS-Studio-Custom-Steps-mockup pull request #3
Opened 2022-08-17 14:04 UTC by SASdemo-contributor

# Please include answers to these questions as part of your pull request

For each question simply place an **X**  in the square brackets, \[X\], that represents your answer

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [ ] Yes, I have the right to submit code and agree to releasing the code under the Apache 2.0 license 
   - [X ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [ ] My contribution does NOT include PII data
   - [X] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [ ] My contribution does NOT contain encryption or other export-controlled technology
   - [X] My contribution includes encryption or other export-controlled technology

2022-08-17 14:13 UTC, SASdemo-maintainer2 requested changes
Please add screenshots for all your user-defined tabs.

2022-08-17 14:37 UTC, SASdemo-maintainer2 requested changes

2022-08-17 14:37 UTC, SASdemo-maintainer2 commented on MyCustomStep01/README.md
> +* Options tab
Please add screenshots for all your user-defined tabs, screenshot for tab xyz seems to be missing.

2022-08-23 12:33 UTC, SASdemo-contributor commented on MyCustomStep01/README.md
> +* Options tab
It is there now.

2022-08-23 12:35 UTC, merged